name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    # nrwl's CI script: https://github.com/nrwl/ci
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.5
    with:
      number-of-agents: 3
      parallel-commands: |
        npx nx-cloud record -- npx nx workspace-lint
        npx nx-cloud record -- npx nx format:check
      parallel-commands-on-agents: |
        npx nx affected --target=lint --parallel=2
        npx nx affected --target=test --parallel=2 --ci --code-coverage
        npx nx affected --target=build --parallel=2

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.5
    with:
      number-of-agents: 2
