name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    # nrwl's CI script: https://github.com/nrwl/ci
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.9
    with:
      number-of-agents: 1
      parallel-commands: npx nx-cloud record -- npx nx lint
      parallel-commands-on-agents: |
        npx nx affected --target=test --parallel=1 --ci --code-coverage
        npx nx affected --target=build --parallel=1

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.9
    with:
      number-of-agents: 1
