name: release

on:
  - workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "GitHub Bot"
          git config user.email "gituser@example.com"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.19.3'
      - run: npm ci

      - name: Version and Publishment
        run: npx nx version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Tag last-release
        shell: bash
        run: |
          git tag -f last-release
          git push origin last-release --force
